### ISSUE TITLE
상품 기능 개발

### ISSUE THREAD

**Issue by smileboy0014** [FC-InnerCircle/icd01-team05_06-commerce-be#3]

**Comment by psh10066** [comment]
<img width="1107" alt="스크린샷 2024-08-29 오후 7 35 58" src="https://github.com/user-attachments/assets/9116d50e-9e11-43f4-96cf-a29ce61d2846">
<img width="808" alt="image" src="https://github.com/user-attachments/assets/db9bb3ac-d46b-4eb8-93aa-0a0468f593d0">
